import: {
  import_name: "India_LifeExpectancy"
  provenance_url: "https://ndap.niti.gov.in/dataset/7375"
  category: STATS
  provenance_description: "Life expectancy of a person in India based on gender at state level."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/india_ndap/ndap/latest/graph.tfrecord@1.gz"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/india_ndap/ndap/latest/India_LifeExpectancy.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/india_ndap/ndap/latest/India_LifeExpectancy.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/india_ndap/ndap/India_LifeExpectancy/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/india_ndap/ndap/India_LifeExpectancy/import_metadata_mcf.mcf"
  import_groups: "country"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  dataset_name: "India Life Expectancy by State"
}
