import {
  import_name: "Denmark_Demographics"
  provenance_url: "https://www.statbank.dk/statbank5a/default.asp?w=1280"
  category: STATS
  provenance_description: "Population data for Denmark from StatBank"
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/denmark/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/denmark/latest/population_sex_age_time_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/denmark/latest/*_output.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/denmark_demographics/Denmark_Demographics/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/denmark_demographics/Denmark_Demographics/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "Denmark Demographics"
}
