import {
  import_name: "Finland_Census"
  provenance_url: "https://pxdata.stat.fi/PxWeb/pxweb/en/StatFin/StatFin__vaerak/statfin_vaerak_pxt_11ra.px/table/tableViewLayout1/"
  category: STATS
  provenance_description: "Population data for Finland"
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/finland/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/finland/finland_census_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/finland/finland_census_output.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/finland_census/Finland_Census/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/finland_census/Finland_Census/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  dataset_name: "Finland Census"
}
