import {
  import_name: "Ireland_Census"
  provenance_url: "https://www.cso.ie/en/index.html"
  category: STATS
  provenance_description: "Ireland Demographics, Health and Economy data from Central Statistics Office(CSO) by country, county and city."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/ireland/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/ireland/latest/irl_aa1_aa2_employment_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/ireland/latest/*.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/ireland_census/Ireland_Census/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/ireland_census/Ireland_Census/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P5Y"
  dataset_name: "Ireland Census"
}
