import {
  import_name: "OECD_Waste_Water_Treatment"
  provenance_url: "https://www.oecd.org/"
  category: STATS
  provenance_description: "Population connected to the waste water treatment using different methods from the Organisation for Economic Co-operation and Development (OECD) for different countries."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/oecd_wastewater_treatment/latest/graph.tfrecord@1.gz"
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/oecd/wastewater_treatment/OECD_Waste_Water_Treatment/import_metadata_mcf.mcf"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/oecd_wastewater_treatment/latest/oecd_wastewatertreatment.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/oecd_wastewater_treatment/latest/oecd_wastewatertreatment.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/oecd/wastewater_treatment/OECD_Waste_Water_Treatment/latest_version.txt"
    }
  }
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  dataset_name: "OECD Waste Water Treatment"
}
