import: {
  import_name: "OECDRegionalDemography_Deaths"
  provenance_url: "https://data-explorer.oecd.org/vis?df[ds]=DisseminateFinalDMZ&df[id]=DSD_REG_DEMO%40DF_DEATH_5Y&df[ag]=OECD.CFE.EDS&df[vs]=2.0&dq=A.......&to[TIME_PERIOD]=false&pd=%2C"
  category: STATS
  provenance_description: "Deaths statistics by age and sex measured by OECD."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/regional_demography/deaths/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/deaths/latest/OECD_deaths_cleaned.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/deaths/latest/OECD_deaths_cleaned.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/oecd/regional_demography/deaths/OECDRegionalDemography_Deaths/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/oecd/regional_demography/deaths/OECDRegionalDemography_Deaths/import_metadata_mcf.mcf"
  #Retained dataset
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/regional_demography/deaths/retained/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/deaths/retained/OECD_deaths_retained.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/deaths/retained/OECD_deaths_retained.csv"
  }
  import_groups: "auto1w"
  automated_mcf_generation_by: "auto1w"
  import_groups: "laelaps"
  import_groups: "searchaim"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "OECD Regional Demography Statistics Deaths"
}
