import: {
  import_name: "OECDRegionalEducation"
  provenance_url: "https://stats.oecd.org/Index.aspx?DataSetCode=REGION_EDUCAT"
  category: STATS
  provenance_description: "OECD 2024, OECD Regional Education Statistics, url:https://stats.oecd.org/Index.aspx?DataSetCode=REGION_EDUCATaccessed on 01/17/2024."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/oecd_education/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/oecd_education/latest/oecd_regional_education.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/oecd_education/latest/oecd_regional_education.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/oecd/regional_education/OECDRegionalEducation/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/oecd/regional_education/OECDRegionalEducation/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  dataset_name: "OECD Regional Education Statistics"
}
