import {
  import_name: "SouthKorea_Health"
  provenance_url: "https://kosis.kr/eng/statisticsList/statisticsListIndex.do"
  category: STATS
  provenance_description: "This data is from the South Korea Statistics Agency (KOSA), that describes about the health statistics of South Korea."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/southkorea/health/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/southkorea/health/health.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/southkorea/health/health.csv"
  }
  import_groups: "country"
  start_date_in_kg: "2004"
  end_date_in_kg: "2024"
  dataset_name: "South Korea Statistics"
}
