import {
  import_name: "UAE_Population"
  provenance_url: "https://bayanat.ae/en/Data?query=population"
  category: STATS
  provenance_description: "Demographic statistics and population estimates for the United Arab Emirates."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/uae_bayanat/population/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/uae_bayanat/population/latest/uae_population_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/uae_bayanat/population/latest/uae_population_output.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/uae_bayanat/uae_population/UAE_Population/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/uae_bayanat/uae_population/UAE_Population/import_metadata_mcf.mcf"
  import_groups: "country"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "UAE Population"
}
