import: {
  import_name: "UnitedKingdomMHCLG_IMD2019"
  provenance_url: "https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019"
  category: STATS
  provenance_description: "Index of Multiple Deprivation 2019 measuring relative deprivation across small areas in England."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/uk/mhclg/nodes.mcf@1"
  import_groups: "infrequent"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "IMD2019"
}
