import: {
  import_name: "WHO_TuberculosisAndHIVTreatmentOutcome"
  provenance_url: "https://data.who.int/indicators/i/DCDC2EB/625E736"
  category: STATS
  provenance_description: "Percentage of people with TB/HIV who started dug-susceptible tuberculosis treatment and whose treatment outcome was recorded as treatment success (cured or treatment completed), treatment failed, died, lost to follow-up, or not evaluated, within the reporting period."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/who/treatement_outcome_tb_hiv/latest/graph.tfrecord@1.gz"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/who/treatement_outcome_tb_hiv/latest/tuberculosis_hiv_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/who/treatement_outcome_tb_hiv/latest/tuberculosis_hiv_output.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/who_tuberculosis/treatmentoutcome_tb_hiv/WHO_TuberculosisAndHIVTreatmentOutcome/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/who_tuberculosis/treatmentoutcome_tb_hiv/WHO_TuberculosisAndHIVTreatmentOutcome/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "WHO Tuberculosis And HIV Treatment Outcome"
}
