import: {
  import_name: "EurostatData_Demographic_Balance_Crude_Rates"
  provenance_url: "https://ec.europa.eu/eurostat/databrowser/view/demo_r_gind3/default/table?lang=en"
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/eurostat/demographic_balance_crude_rates/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/eurostat/demographic_balance_crude_rates/latest/EurostatNUTS3_BirthDeathMigration.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/eurostat/demographic_balance_crude_rates/latest/EurostatNUTS3_BirthDeathMigration.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/eurostat/regional_statistics_by_nuts/birth_death_migration/EurostatData_Demographic_Balance_Crude_Rates/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/eurostat/regional_statistics_by_nuts/birth_death_migration/EurostatData_Demographic_Balance_Crude_Rates/import_metadata_mcf.mcf"
  import_groups: "laelaps"
  import_groups: "searchaim"
  import_groups: "auto1w"
  automated_mcf_generation_by: "auto1w"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "Regional Statistics by NUTS Classification"
}
