import {
  import_name: "INPE_Fire_Event_Count"
  provenance_url: "https://terrabrasilis.dpi.inpe.br/queimadas/situacao-atual/estatisticas/estatisticas_estados/"
  category: STATS
  provenance_description: "This dataset represents count of occurrence of fire event in Brazil.Data available for Country and state level."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/brazil/INPE_Fire/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/brazil/INPE_Fire/latest/output_inpe.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/brazil/INPE_Fire/latest/output_inpe.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/inpe_fire/INPE_Fire_Event_Count/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/inpe_fire/INPE_Fire_Event_Count/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1M"
  dataset_name: "BRAZIL INPE Fire Event Count"
}
