import: {
  import_name: "NewYork_Education"
  provenance_url: "https://data.cityofnewyork.us/browse?category=Education"
  provenance_description: "Official public data from the NYC Department of Education, including student performance (test scores, graduation rates), school quality metrics, and student demographics across all five boroughs"
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_edu/urban_new_york_education/latest/output/graph.tfrecord@1.gz"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_edu/urban_new_york_education/latest/output/common.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_edu/urban_new_york_education/latest/output/*.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/us_education/new_york_education/NewYork_Education/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/us_education/new_york_education/NewYork_Education/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "NewYork Education"
}
