import: {
  import_name: "NOAA_GPCC_StandardardizedPrecipitationIndex_Event"
  provenance_url: "https://www.drought.gov/data-maps-tools/global-precipitation-climatology-centre-gpcc-standardized-precipitation-index-spi"
  provenance_description: "Events using SPI for 1 degree grids calculated from 9 month precipitation data using the Pearson distribution."
  category: ENTITY
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/noaa/gpcc_spi/events_spi_9m_polygon/latest/events/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/noaa/gpcc_spi/events_spi_9m_polygon/latest/events/drought_spi_9m_polygon_events.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/noaa/gpcc_spi/events_spi_9m_polygon/latest/events/drought_spi_9m_polygon_events.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/noaa/gpcc_spi/NOAA_GPCC_StandardardizedPrecipitationIndex/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/noaa/gpcc_spi/NOAA_GPCC_StandardardizedPrecipitationIndex/import_metadata_mcf.mcf"
  import_groups: "auto1w"
  import_groups: "infrequent"
  automated_mcf_generation_by: "auto1w"
  release_frequency: "P1M"
  resolution_info: { uses_id_resolver: true }
  # Retained data from 1900-2010.
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/noaa/gpcc_spi/events_spi_9m_polygon/retained_1900_2010/events/nodes.mcf@3"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/noaa/gpcc_spi/events_spi_9m_polygon/retained_1900_2010/events/drought_spi_9m_polygon_1901_events.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/noaa/gpcc_spi/events_spi_9m_polygon/retained_1900_2010/events/drought_spi_9m_polygon_*_events.csv"
  }
  dataset_name: "GPCC Monthly SPI Data"
}
