import: {
  import_name: "OECDRegionalDemography_PopulationDensity"
  provenance_url: "https://data-explorer.oecd.org/vis?pg=0&snb=1&tm=pop%20density&df[ds]=dsDisseminateFinalDMZ&df[id]=DSD_REG_DEMO%40DF_DENSITY&df[ag]=OECD.CFE.EDS&df[vs]=2.0&dq=A.......&pd=%2C&to[TIME_PERIOD]=false&vw=tb"
  category: STATS
  provenance_description: "Population density statistics measured by OECD."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/regional_demography/pop_density/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/pop_density/latest/OECD_pop_density_cleaned.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/pop_density/latest/OECD_pop_density_cleaned.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/oecd/regional_demography/pop_density/OECDRegionalDemography_PopulationDensity/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/oecd/regional_demography/pop_density/OECDRegionalDemography_PopulationDensity/import_metadata_mcf.mcf"
  #Retained dataset
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/oecd/regional_demography/pop_density/retained/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/pop_density/retained/OECD_pop_density_retained.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/oecd/regional_demography/pop_density/retained/OECD_pop_density_retained.csv"
  }
  import_groups: "auto1w"
  automated_mcf_generation_by: "auto1w"
  import_groups: "laelaps"
  import_groups: "searchaim"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "OECD Regional Demography Statistics Population Density"
}
