import {
  import_name: "Zurich_Population_By_Sex"
  provenance_url: "https://www.stadt-zuerich.ch/content/dam/web/de/politik-verwaltung/statistik-und-daten/linked-open-data/datacommons/bev_3903_sex_wiki.csv"
  category: STATS
  provenance_description: "Population by sex of Zurich city contains structure and organization of the city administration"
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/zurich/latest/zurich_by_sex/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/zurich/latest/zurich_by_sex/zurich_population_common.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/zurich/latest/zurich_by_sex/zurich_population_bev_3903_sex_wiki.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/zurich/Zurich_Population_By_Sex/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/zurich/Zurich_Population_By_Sex/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "Zurich population"
}
