import: {
  import_name: "Copernicus_ECMWF_ERA5_Monthly_AggrYearsStats"
  provenance_url: "https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels"
  provenance_description: "Aggregated by DataCommons."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/dc_aggregate/StatVarSeries/Aggregates/v2/Copernicus_ECMWF_ERA5_Monthly_AggrYearsStats/graph.tfrecord*"
  import_groups: "ipcc"
  category: INTERMEDIATE_STATS
  dataset_name: "Copernicus ECMWF - ERA5 Climate Reanalysis Data"
}
