import: {
  # NOTE: This dataset includes IPCCPlace_50 entities (0.5 degree resolution)
  # throughout the world.
  import_name: "NASA_NEXGDDP_IpccPlaces50"
  provenance_url: "https://www.nccs.nasa.gov/services/data-collections/land-based-products/nex-gddp"
  category: STATS
  provenance_description: "Global downscaled climate projections (CMIP5) mapped to 50km geographic grids."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/nasa/nex-gddp/ipcc-places-50/graph.tfrecord*"
  import_groups: "ipcc"
  start_date_in_kg: "1950"
  end_date_in_kg: "2099"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/nasa/nex-gddp/ipcc-places-50/ipcc_geo_resolved.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/nasa/nex-gddp/ipcc-places-50/ipcc_geo_resolved-*-of-*"
  }
  dataset_name: "NEX - Global Downscaled Climate Projections from IPCC CMIP5"
}
