import {
  import_name: "GeoBoundaries_Federated_States_of_Micronesia_ADM2"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen/FSM/ADM2"
  category: PLACE
  provenance_description: "Includes the boundary files of the Municipalities (Administrative Area 2 division) of Federated States of Micronesia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/boundaryFiles/Federated_States_of_Micronesia/ADM2/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
