import {
  import_name: "GeoBoundaries_Latvia_ADM2"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen/LVA/ADM2"
  category: PLACE
  provenance_description: "Includes the boundary files of the Administrative Area 2 divisions of Latvia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/boundaryFiles/Latvia/ADM2/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
