import {
  import_name: "GeoBoundaries_Bahamas"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen"
  category: PLACE
  provenance_description: "Includes the boundary files for the Administrative Areas 1 in Bahamas."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geoBoundaries/gbOpen/BHS/ADM1/Boundaries_file/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
