import {
  import_name: "GeoBoundaries_Norway"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen/NOR/ADM1"
  category: PLACE
  provenance_description: "Includes the boundary files of the Administrative Area 1 divisions of Norway."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/boundaryFiles/Norway/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
