import {
  import_name: "GeoBoundaries_Myanmar"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen"
  category: PLACE
  provenance_description: "Includes the provinces(Administrative Area 1 division) of Myanmar."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geoBoundaries/gbOpen/MMR/ADM1/Boundaryfiles/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
