import {
  import_name: "GeoBoundaries_Latvia"
  provenance_url: "https://github.com/wmgeolab/geoBoundaries/tree/main/releaseData/gbOpen/LVA/ADM1"
  category: PLACE
  provenance_description: "Includes the boundary files of the municipalities(Administrative Area 1 division) of Latvia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/boundaryFiles/Latvia/*.mcf"
  import_groups: "place"
  dataset_name: "Global Database of Political Administrative Boundaries Database"
}
