# LINT.IfChange
import: {
  import_name: "GeoCoordinatesData_Simplified"
  provenance_url: "https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.2018.html"
  category: PLACE
  provenance_description: "Lower resolution GeoJSONs derived from the US Census Gazetteer files."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geojson_simplified/*.mcf"
  import_groups: "place"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: false }
  dataset_name: "Cartographic Boundary Files"
}
# LINT.ThenChange(//depot/google3/production/borg/datcom/prophet/generator/import_group.borg)
#   - This needs a rebuild of the coordinate recon cache, and updating --coordinate_recon_cache_path
