import {
  import_name: "NCES_PublicSchool"
  provenance_url: "https://nces.ed.gov/ccd/elsi/tableGenerator.aspx"
  category: PLACE
  provenance_description: "Public Schools place addition in US."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_nces/demographics/public_school/public_place/latest/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/public_place/latest/us_nces_demographics_public_place.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/public_place/latest/us_nces_demographics_public_place.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_nces/demographics/public_school/NCES_PublicSchool/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_nces/demographics/public_school/NCES_PublicSchool/import_metadata_mcf.mcf"
  # PublicSchool -> City containment computed from this SQL query:
  #   http://gpaste/5406956217958400
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_nces/demographics/public_school/city_containment/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/city_containment/school_in_city.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/city_containment/school_in_city.csv"
  }
  # Additional types for the schools (to handle queries like high school using
  # existing frontend tiles) computed from this SQL query:
  #   http://gpaste/4613625997164544
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_nces/demographics/public_school/additional_school_types/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/additional_school_types/additional_school_types.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/public_school/additional_school_types/additional_school_types.csv"
  }
  import_groups: "place"
  resolution_info: {
    uses_id_resolver: false
    provides_ids: "ncesId"
    new_geo {
      dcid_sources: "ncesId"
    }
  }
  dataset_name: "Public School and School District Data"
}
