import {
  import_name: "OCHAGeoCoordinates_Ukraine"
  provenance_url: "https://data.humdata.org/dataset/cod-ab-ukr"
  category: PLACE
  provenance_description: "Includes the boundary files for Administrative areas 1 in Ukraine."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Ukraine/Boundaryfiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
