import {
  import_name: "OCHAGeoCoordinates_Madagascar"
  provenance_url: "https://data.humdata.org/dataset/whosonfirst-data-admin-mdg"
  category: PLACE
  provenance_description: "Includes administratrive area 1 place boundaries for Madagascar"
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/madagascar/BoundaryFiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
