import {
  import_name: "OCHAGeoCoordinates_Bahrain"
  provenance_url: "https://data.humdata.org/dataset/cod-ab-bhr"
  category: PLACE
  provenance_description: "Includes the boundary files for the districts(Administrative Area 1 division) in Bahrain."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/bahrain/Boundaryfiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
