import {
  import_name: "OCHAGeoCoordinates_Gabon"
  provenance_url: "https://data.humdata.org/dataset/whosonfirst-data-admin-gab"
  category: PLACE
  provenance_description: "Includes administratrive area 1 places of Gabon."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Gabon/BoundaryFiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
