import {
  import_name: "OCHAGeoCoordinates_Guinea_Bissau_ADM2"
  provenance_url: "https://data.humdata.org/dataset/cod-ab-gnb"
  category: PLACE
  provenance_description: "Includes the boundary files for the Administrative Area 2 divisions of Guinea-Bissau."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/guinea-bissau/BoundaryFiles_ADM2/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
