import {
  import_name: "OCHAGeoCoordinates_Switzerland_ADM2"
  provenance_url: "https://data.humdata.org/dataset/whosonfirst-data-admin-che"
  category: PLACE
  provenance_description: "Includes the boundary files for the Administrative Area 2 divisions of Switzerland."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Switzerland/BoundaryFiles_ADM2/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
