import {
  import_name: "OCHAGeoCoordinates_Croatia"
  provenance_url: "https://data.humdata.org/dataset/whosonfirst-data-admin-hrv"
  category: PLACE
  provenance_description: "Includes the boundary files for the counties(Administrative Area 1 division) in Croatia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Croatia/Boundaryfiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
