import {
  import_name: "OCHAGeoCoordinates_Gambia"
  provenance_url: "https://data.humdata.org/dataset/cod-ab-gmb"
  category: PLACE
  provenance_description: "Includes the boundary files for the regions(Administrative Area 1 division) in Gambia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Gambia/BoundaryFiles/*.mcf"
  import_groups: "place"
  dataset_name: "UN OCHA Subnational Administrative Boundaries"
}
