import {
  import_name: "WikidataGeo_France"
  provenance_url: "https://en.wikipedia.org/wiki/Regions_of_France"
  category: PLACE
  provenance_description: "Includes the Administrative Area 1 divisions of France."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/France/ADM1/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/France/ADM1/wikidata/fra.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/France/ADM1/wikidata/France-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
