import {
  import_name: "WikidataGeo_Croatia"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the counties(Administrative Area 1 division) of Croatia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Croatia/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Croatia/wikidata/Croatia.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Croatia/wikidata/Croatia_ADM1_sheet-final .csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
