import {
  import_name: "WikidataGeo_NewZealand"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the regions(Administrative Area 1 division) of NewZealand."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/NewZealand/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/NewZealand/NewZealand.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/NewZealand/NewZealand_final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
