import {
  import_name: "WikidataGeo_Brazil_AA1"
  provenance_url: "https://en.m.wikipedia.org/wiki/Federative_units_of_Brazil"
  category: PLACE
  provenance_description: "Includes the Administrative Area 1 divisions of Brazil."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Brazil/ADM1/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Brazil/ADM1/Brazil.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Brazil/ADM1/Brazil_ADM1-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
