import {
  import_name: "WikidataGeo_Gabon"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes administratrive area 1 places of Gabon."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Gabon/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Gabon/gabon.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Gabon/Gabon_ADM1_Final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
