import {
  import_name: "WikidataGeo_Singapore"
  provenance_url: "https://en.wikipedia.org/wiki/Regions_of_Singapore"
  category: PLACE
  provenance_description: "Includes the Administrative Area 1 divisions of Singapore."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Singapore/ADM1/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Singapore/ADM1/wikidata/SGP.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Singapore/ADM1/wikidata/Singapore_ADM1-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
