import {
  import_name: "WikidataGeo_CapeVerde"
  provenance_url: "https://en.m.wikipedia.org/wiki/Administrative_divisions_of_Cape_Verde"
  category: PLACE
  provenance_description: "Includes the Administrative Areas 1 of CapeVerde."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/CapeVerde/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/CapeVerde/wikidata/CapeVerde.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/CapeVerde/wikidata/CPV_ADM1-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
