import {
  import_name: "WikidataGeo_Afghanistan"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the provinces(Administrative Area 1 division) of Afghanistan."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Afghanistan/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Afghanistan/afg.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Afghanistan/Afghanistan-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
