import {
  import_name: "WikidataGeo_Gambia"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the regions(Administrative Area 1 division) of Gambia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Gambia/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Gambia/wikidata/gmb.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Gambia/wikidata/Gambia-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
