import {
  import_name: "WikidataGeo_Estonia"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the Administrative Area 1 of Estonia."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Estonia/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Estonia/estonia.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Estonia/"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
