import {
  import_name: "WikidataGeo_Zurich_ADM3"
  provenance_url: "https://en.wikipedia.org/wiki/Subdivisions_of_Zurich"
  category: PLACE
  provenance_description: "Includes the Administrative Area 3 divisions of Zurich."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Zurich/ADM3/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Zurich/ADM3/Zurich.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Zurich/ADM3/Zurich_ADM3-final_sheet.csv"
  }
  import_groups: "place"
  dataset_name: "Zurich GeoCoordinates"
}
