import {
  import_name: "WikidataGeo_Switzerland_ADM2"
  provenance_url: "https://en.wikipedia.org/wiki/Districts_of_Switzerland"
  category: PLACE
  provenance_description: "Includes the Administrative Area 2 divisions of Switzerland."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Switzerland/wikidata_ADM2/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Switzerland/wikidata_ADM2/che.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Switzerland/wikidata_ADM2/Switzerland_ADM2-final_sheet.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
