import {
  import_name: "WikidataGeo_Tonga"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes the provinces (Administrative Area 1 division) of Tonga."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Tonga/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Tonga/wikidata/ton.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Tonga/wikidata/Tonga-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
