import {
  import_name: "WikidataGeo_Qatar"
  provenance_url: "https://www.wikidata.org/"
  category: PLACE
  provenance_description: "Includes administratrive area 1 places of Qatar."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/Qatar/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Qatar/qatar.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/Qatar/Qatar_ADM1 - Final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
