import {
  import_name: "WikidataGeo_Greenland"
  provenance_url: "https://en.wikipedia.org/wiki/Administrative_divisions_of_Greenland"
  category: PLACE
  provenance_description: "Includes the municipalities (Administrative Area 1 division) of Greenland."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ocha/geodata/Greenland/wikidata/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Greenland/wikidata/grl.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ocha/geodata/Greenland/wikidata/Greenland-final.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
