import {
  import_name: "WikidataGeo_CapeVerde_ADM2"
  provenance_url: "https://en.wikipedia.org/wiki/Administrative_divisions_of_Cape_Verde"
  category: PLACE
  provenance_description: "Includes the Administrative Area 2 divisions of Cape Verde."
  mcf_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/geos/BaseGeos/wikidata/CapeVerde/ADM2/nodes.mcf@1"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/CapeVerde/ADM2/Capeverde.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/geos/BaseGeos/wikidata/CapeVerde/ADM2/CapeVerde_ADM2-final_sheet.csv"
  }
  import_groups: "place"
  dataset_name: "Wikidata"
}
