import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2409"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2409&tid=ACSST1Y2023.S2409"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2409: Industry by Sex for the Civilian Employed Population."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2409/20250129/graph.tfrecord@8.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2409/20250129/s2409_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2409/20250129/s2409_cleaned.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
