import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2601APR"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2601APR&tid=ACSST5Y2023.S2601APR"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2601APR: Characteristics of the Group Quarters Population in Puerto Rico."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2601apr/20250206/graph.tfrecord@1.gz"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2601apr/20250206/S2601apr_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2601apr/20250206/S2601apr_cleaned.csv"
  }
  import_groups: "uscensus"
  dataset_name: "American Community Survey (ACS)"
}
