import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2703"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2703&tid=ACSST5Y2023.S2703"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2703: Private Health Insurance Coverage by Type."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2703/20250203/graph.tfrecord@6.gz"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2703/20250203/s2703_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2703/20250203/s2703_cleaned.csv"
  }
  import_groups: "uscensus"
  start_date_in_kg: "2015"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "American Community Survey (ACS)"
}
