import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2701"
  provenance_url: "https://data.census.gov/table/ACSST5Y2024.S2701?q=S2701"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2701: Selected Characteristics of Health Insurance Coverage in the United States."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/S2701/20260414/graph.tfrecord@2.gz"
  resolution_info: { uses_id_resolver: true }
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/S2701/20260414/s2701_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/S2701/20260414/*.csv"
  }
  import_groups: "uscensus"
  start_date_in_kg: "2012"
  end_date_in_kg: "2024"
  dataset_name: "American Community Survey (ACS)"
}
