import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2408"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2408: Class of Worker by Sex for the Civilian Employed Population."
  provenance_url: "https://data.census.gov/cedsci/table?q=S2408&tid=ACSST5Y2023.S2408"
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2408/20250120/graph.tfrecord@10.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2408/20250120/s2408_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2408/20250120/s2408_cleaned.csv"
  }
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "American Community Survey (ACS)"
}
