import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2702PR"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2702PR&tid=ACSST5Y2013.S2702PR"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2702PR: Selected Characteristics of Health Insurance Coverage in Puerto Rico."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2702PR/20250211/graph.tfrecord@1.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2013"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2702PR/20250211/s2702PR_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2702PR/20250211/s2702PR_cleaned.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
