import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2502"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2502&tid=ACSST5Y2023.S2502"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2502: Demographic Characteristics for Occupied Housing Units."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2502/s2502_20250213/graph.tfrecord@23.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2502/s2502_20250213/s2502_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2502/s2502_20250213/*.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
