import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S0701"
  provenance_url: "https://data.census.gov/cedsci/table?q=S0701&tid=ACSST5Y2024.S0701"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S0701: Geographic Mobility by Selected Characteristics in the United States."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s0701/20260325/graph.tfrecord@169.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2024"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s0701/20260325/S0701_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s0701/20260325/*_output.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
