import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2405"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2405&tid=ACSST5Y2023.S2405"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2405: Industry by Occupation for the Civilian Employed Population."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2405/20250127/graph.tfrecord@15.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2405/20250127/S2405_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2405/20250127/*.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
