import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S0503"
  provenance_url: "https://data.census.gov/cedsci/table?q=S0503&tid=ACSST5Y2023.S0503"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S0503: Selected Characteristics of the Foreign-Born Population by Region of Birth: Europe."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/S0503/20250228/graph.tfrecord@5.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/S0503/20250228/S0503_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/S0503/20250228/S0503_cleaned.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
