import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2407"
  provenance_url: "https://data.census.gov/cedsci/table?q=S2407&tid=ACSST5Y2023.S2407"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2407: Industry by Class of Worker for the Civilian Employed Population."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2407/20250205/graph.tfrecord@23.gz"
  import_groups: "uscensus"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2407/20250205/S2407_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2407/20250205/S2407_cleaned_*.csv"
  }
  dataset_name: "American Community Survey (ACS)"
}
