import: {
  import_name: "CensusACS5YearSurvey_SubjectTables_S2201"
  provenance_url: "https://data.census.gov/table/ACSST5Y2023.S2201?q=S2201"
  category: STATS
  provenance_description: "ACS 5-Year Subject Table S2201: Food Stamps/Supplemental Nutrition Assistance Program (SNAP)."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/census/acs5yr/subject_tables/s2201/20250123/graph.tfrecord@32.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2201/20250123/output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/census/acs5yr/subject_tables/s2201/20250123/output.csv"
  }
  import_groups: "uscensus"
  import_groups: "laelaps"
  start_date_in_kg: "2010"
  end_date_in_kg: "2023"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "American Community Survey (ACS)"
}
