import: {
  import_name: "Commerce_EDA"
  provenance_url: "https://www.commerce.gov/bureaus-and-offices/eda"
  category: STATS
  provenance_description: "Data regarding economic development grants, investments, and programmatic activities from the US Economic Development Administration."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_eda/latest/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_eda/latest/poverty_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_eda/latest/*.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/commerce_eda/Commerce_EDA/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/commerce_eda/Commerce_EDA/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "Economic Development Administration (EDA)"
}
