import: {
  import_name: "USBTS_Tract_Household_Transportation"
  provenance_url: "https://www.bts.dot.gov/latch/latch-data"
  provenance_description: "The import brings the data for tract transport characteristics for household in US."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_bts/latch/latest/gcs_output/output_files/graph.tfrecord@2.gz"
  category: STATS
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_bts/latch/latest/gcs_output/output_files/us_transportation_household.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_bts/latch/latest/gcs_output/output_files/*.csv"
    download_config {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_bts/latch/USBTS_Tract_Household_Transportation/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_bts/latch/USBTS_Tract_Household_Transportation/import_metadata_mcf.mcf"
  dataset_name: "US Tract Transportation Characteristics for Households"
}
