import: {
  import_name: "USCensusPEP_AgeSexRace"
  provenance_url: "https://www2.census.gov/programs-surveys/popest/tables"
  category: STATS
  provenance_description: "Annual US population estimates broken down by detailed age, sex, and race categories."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_census/pep/population_estimate_by_asr/latest/graph.tfrecord@4.gz"
  import_groups: "uscensus"
  import_groups: "auto1w"
  import_groups: "laelaps"
  start_date_in_kg: "1900"
  end_date_in_kg: "2023"
  end_date_in_source: "2023"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  automated_mcf_generation_by: "auto1w"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_census/pep/population_estimate_by_asr/latest/usa_population_asr.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_census/pep/population_estimate_by_asr/latest/usa_population_asr.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_census/pep/population_estimates_by_asr/USCensusPEP_AgeSexRace/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_census/pep/population_estimates_by_asr/USCensusPEP_AgeSexRace/import_metadata_mcf.mcf"
  dataset_name: "Population Estimates Program (PEP)"
}
