import: {
  import_name: "USCensusPEP_MonthlyPopulation"
  provenance_url: "https://www.census.gov/programs-surveys/popest.html"
  provenance_description: "US Census Population Estimates Program (PEP)."
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_census/pep/monthly_population_estimate/latest/graph.tfrecord@1.gz"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_census/pep/monthly_population_estimate/latest/USA_Population_Count.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_census/pep/monthly_population_estimate/latest/USA_Population_Count.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_census/pep/monthly_population_estimate/USCensusPEP_MonthlyPopulation/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_census/pep/monthly_population_estimate/USCensusPEP_MonthlyPopulation/import_metadata_mcf.mcf"
  import_groups: "laelaps"
  import_groups: "auto1w"
  release_frequency: "P1Y"
  automated_mcf_generation_by: "auto1w"
  resolution_info: { uses_id_resolver: true }
  #cachedSourceDataUrl:  "unresolved_mcf/us_census/pep/monthly_population_estimate/20231211"
  #processingScript: "https://github.com/datacommonsorg/data/tree/master/scripts/us_census/pep"
  dataset_name: "Population Estimates Program (PEP)"
}
