import: {
  import_name: "BEA_USStatesQuarterlyGDP"
  provenance_url: "https://www.bea.gov/data/gdp/gdp-state"
  category: STATS
  provenance_description: "Quarterly data on inflation-adjusted GDP at a state level in the United States from the US Bureau of Economic Analysis."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_bea/states_gdp/20250509/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_bea/states_gdp/20250509/states_gdp.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_bea/states_gdp/20250509/states_gdp.csv"
  }
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_bea/states_industries_gdp/20250509/graph.tfrecord@1.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_bea/states_industries_gdp/20250509/states_industry_gdp.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_bea/states_industries_gdp/20250509/states_industry_gdp.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_bea/states_gdp/BEA_USStatesQuarterlyGDP/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_bea/states_gdp/BEA_USStatesQuarterlyGDP/import_metadata_mcf.mcf"
  import_groups: "infrequent"
  import_groups: "searchaim"
  import_groups: "auto2w"
  start_date_in_kg: "2005-03"
  end_date_in_kg: "2024-12"
  release_frequency: "P3M"
  next_release_date: "2025"
  automated_mcf_generation_by: "auto2w"
  data_download_url: "https://www.bea.gov/data/gdp/gdp-state"
  resolution_info: { uses_id_resolver: true }
  # TODO(wsws): Remove after getting all the unresolved MCFs in CNS.
  is_unresolved_mcf_missing: true
  dataset_name: "Gross Domestic Product"
}
