import: {
  import_name: "CDC_StandardizedPrecipitationEvapotranspirationIndex"
  provenance_url: "https://data.cdc.gov/Environmental-Health-Toxicology/Standardized-Precipitation-Evapotranspiration-Inde/6nbv-ifib"
  category: STATS
  provenance_description: "Standardized Precipitation Evapotranspiration Index (SPEI) data for measuring drought severity."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/cdc/environmental/StandardizedPrecipitationEvapotranspirationIndex/latest/graph.tfrecord@1.gz"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/cdc/environmental/StandardizedPrecipitationEvapotranspirationIndex/latest/StandardizedPrecipitationEvapotranspirationIndex.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/cdc/environmental/StandardizedPrecipitationEvapotranspirationIndex/latest/CDC_StandardizedPrecipitationEvapotranspirationIndex_output.csv"
    download_config {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_cdc/cdc_standardized_precipitation/evapotranspiration_index/CDC_StandardizedPrecipitationEvapotranspirationIndex/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_cdc/cdc_standardized_precipitation/evapotranspiration_index/CDC_StandardizedPrecipitationEvapotranspirationIndex/import_metadata_mcf.mcf"
  dataset_name: "Environmental Health Toxicology"
}
