import: {
  import_name: "EIA_TotalEnergy"
  provenance_url: "https://www.eia.gov/opendata/qb.php?category=711224"
  category: STATS
  provenance_description: "Total US energy statistics detailing comprehensive energy flow from primary energy production to end-use consumption."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_eia/total_energy/latest/graph.tfrecord@1.gz"
  import_groups: "auto2w"
  import_groups: "infrequent"
  automated_mcf_generation_by: "auto2w"
  data_download_url: "http://api.eia.gov/bulk/TOTAL.zip"
  resolution_info: { uses_id_resolver: true }
  release_frequency: "P1Y"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_eia/total_energy/latest/TOTAL.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_eia/total_energy/latest/TOTAL.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_eia/opendata/EIA_TotalEnergy/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_eia/opendata/EIA_TotalEnergy/import_metadata_mcf.mcf"
  dataset_name: "Open Data"
}
