import: {
  import_name: "EPA_USAirPollutantEmissionTrends_NationalAndState"
  provenance_url: "https://www.epa.gov/air-emissions-inventories/air-pollutant-emissions-trends-data"
  provenance_description: "The import has variables that are directly available from EPA source for Air Pollution Emissions."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_epa/air_emissions_inventory/national_state/latest/graph.tfrecord@1.gz"
  category: STATS
  import_groups: "infrequent"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_epa/air_emissions_inventory/national_state/latest/airpollution_emission_trends_tier1.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_epa/air_emissions_inventory/national_state/latest/airpollution_emission_trends_tier1.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_epa/air_emissions_inventory/national_state/EPA_USAirPollutantEmissionTrends_NationalAndState/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_epa/air_emissions_inventory/national_state/EPA_USAirPollutantEmissionTrends_NationalAndState/import_metadata_mcf.mcf"
  dataset_name: "National Emissions Inventory"
}
