import: {
  import_name: "EPAAirQualityIndex"
  provenance_url: "https://aqs.epa.gov/aqsweb/airdata/download_files.html"
  category: STATS
  provenance_description: "Daily Air Quality Index (AQI) values across the US reporting air pollution levels and health concerns."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/epa/airdata/aqi/latest/graph.tfrecord@2.gz"
  import_groups: "infrequent"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  release_frequency: "P6M"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/epa/airdata/aqi/latest/EPA_AQI.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/epa/airdata/aqi/latest/EPA_AQI.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_epa/airqualityindex/EPAAirQualityIndex/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_epa/airqualityindex/EPAAirQualityIndex/import_metadata_mcf.mcf"
  dataset_name: "Air Data"
}
