import: {
  import_name: "FireWFIGS_AggregatedAreas"
  provenance_url: "https://data-nifc.opendata.arcgis.com/"
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/fire/wfigs/fire_areas/graph.tfrecord*"
  import_groups: "experimental"
  provenance_description: "The Wildland Fire Interagency Geospatial Services (WFIGS) Group provides authoritative geospatial data products under the interagency Wildland Fire Data Program. This dataset provides areas for all reported wildland fires in the United States at county, state and country level."
  start_date_in_kg: "2014"
  end_date_in_kg: "2023"
  release_frequency: "P1D"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/fire/wfigs/fire_areas/wfigs_areas.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/fire/wfigs/fire_areas/fire_aggregate_areas.csv"
  }
  dataset_name: "WFIGS Wildland Fire Areas"
}
