import {
  import_name: "NCES_SchoolDistrictStats"
  provenance_url: "https://nces.ed.gov/ccd/elsi/tableGenerator.aspx"
  category: STATS
  provenance_description: "Schools District Demographics in US consisting of count of teacher and count of student across different grade and race."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/us_nces/demographics/school_district/latest/graph.tfrecord@5.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/school_district/latest/us_nces_demographics_district_school.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/us_nces/demographics/school_district/latest/us_nces_demographics_district_school.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/scripts/us_nces/demographics/school_district/NCES_SchoolDistrictStats/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/scripts/us_nces/demographics/school_district/NCES_SchoolDistrictStats/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  resolution_info: {
    uses_id_resolver: false
    provides_ids: "ncesId"
    new_geo {
      dcid_sources: "ncesId"
    }
  }
  dataset_name: "Public School and School District Data"
}
