import: {
  import_name: "NCSES_DoctorateDegreeEmployment"
  provenance_url: "https://ncses.nsf.gov/pubs/nsf19304/data"
  category: STATS
  provenance_description: "Science,engineering and health doctorate holders employed in universities and 4-year colleges by broad occupation,sex,race,ethnicity and tenure status"
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ncses/NCSES_DoctorateDegreeEmployment/latest/graph.tfrecord@1.gz"
  table: {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ncses/NCSES_DoctorateDegreeEmployment/latest/doctoratedegreeemployment.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ncses/NCSES_DoctorateDegreeEmployment/latest/doctoratedegreeemployment.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/doctoratedegreeemployment/NCSES_DoctorateDegreeEmployment/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/doctoratedegreeemployment/NCSES_DoctorateDegreeEmployment/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  release_frequency: "P1Y"
  automated_mcf_generation_by: "auto2w"
  resolution_info: { uses_id_resolver: true }
  dataset_name: "National Center for Science and Engineering Statistics"
}
