import: {
  import_name: "RFF_ClimateWildfireSmoke_MTBS"
  import_groups: "infrequent"
  provenance_url: "https://www.mtbs.gov"
  category: STATS
  provenance_description: "Statistics on burned areas and wildfire perimeters sourced from the Monitoring Trends in Burn Severity (MTBS) project."
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/rff/wildfire_smoke/mtbs/graph.tfrecord@10.gz"
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/rff/wildfire_smoke/mtbs/mtbs.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/rff/wildfire_smoke/fire_and_smoke_v2.csv"
  }
  resolution_info { uses_id_resolver: true }
  dataset_name: "US Wildfire, Smoke and Drought statistics - County and State"
}
