import: {
  import_name: "US_CCD_Enrollment"
  provenance_url: "https://nces.ed.gov/programs/digest/d24/tables/dt24_203.65.asp"
  provenance_description: "Enrollment in public elementary and secondary schools, by level, grade, and race/ethnicity."
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/ccd/enrollment/latest/graph.tfrecord@1.gz"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/ccd/enrollment/latest/CCD_Enrollment_output.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/ccd/enrollment/latest/CCD_Enrollment_output.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/ccd/enrollment/US_CCD_Enrollment/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/ccd/enrollment/US_CCD_Enrollment/import_metadata_mcf.mcf"
  import_groups: "uscensus"
  dataset_name: "US Student Enrollment Data"
}
