import: {
  import_name: "US_SAT_ACT_Participation"
  provenance_url: "https://ocrdata.ed.gov/"
  provenance_description: "This dataset contains participation in Scholastic Assessment Test or American College Testing for each school by students' race and sex,  Limited English Proficiency status and sex, and disability status and sex."
  category: STATS
  mcf_proto_url: "/cns/jv-d/home/datcom/v3_resolved_mcf/country/us_education/us_urbaneducation_school/school_sat_and_act_participation/sat_act_school/latest/graph.tfrecord@2.gz"
  release_frequency: "P1Y"
  resolution_info: { uses_id_resolver: true }
  table {
    mapping_path: "/cns/jv-d/home/datcom/v3_mcf/country/us_education/us_urbaneducation_school/school_sat_and_act_participation/sat_act_school/latest/output_2012.tmcf"
    csv_path: "/cns/jv-d/home/datcom/v3_mcf/country/us_education/us_urbaneducation_school/school_sat_and_act_participation/sat_act_school/latest/output_*.csv"
    download_config: {
      src_latest_version_file: "/bigstore/datcom-prod-imports/statvar_imports/us_urban_school/sat_act_participation/school/US_SAT_ACT_Participation/latest_version.txt"
    }
  }
  metadata_mcf_url: "/bigstore/datcom-prod-imports/statvar_imports/us_urban_school/sat_act_participation/school/US_SAT_ACT_Participation/import_metadata_mcf.mcf"
  import_groups: "auto2w"
  automated_mcf_generation_by: "auto2w"
  dataset_name: "U.S. Department of Education: Urban Education Data Census"
}
